{% set name = "rpaframework-pdf" %}
{% set version = "7.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rpaframework_pdf-{{ version }}.tar.gz
  sha256: 2b25943eca0bc6b414986243de71ae2db2a94815c3351ee11834be4e651bbe3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - rpaframework-core >=11.0.0,<12.0.0
    - robotframework >=4.0.0,!=4.0.1,!=6.1.0,<7.0.0
    - robotframework-pythonlibcore >=4.2.0,<5.0.0
    - pdfminer.six 20221105
    - pypdf >=3.15.0,<4.0.0
    - fpdf2 >=2.7.3,<3.0.0

test:
  imports:
    - RPA
    - RPA.PDF
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rpaframework.org/
  summary: PDF library of RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
